name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [
          macos-11, macos-12, macOS-latest,
          windows-2019, windows-2022, windows-latest,
          ubuntu-20.04, ubuntu-22.04, ubuntu-latest,
        ]
        python-version: [
          '3.7', '3.8', '3.9', '3.10', '3.11', '3.12',
          'pypy3.7', 'pypy3.8', 'pypy3.9', 'pypy3.10',
        ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/setup-python@v5~
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          pip install --upgrade pip
          pip install --upgrade maturin
          pip install --upgrade cffi
          maturin build --release --sdist --features pyo3
          ls -R target/wheels/
      - uses: actions/upload-artifact@v3
        with:
          name: wheel-${{ matrix.platform }}-${{ matrix.python-version }}
          path: target/wheels/
  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: temp
      - run: |
          ls -R temp
          mkdir dist
          for x in temp/*; do mv $x/* dist/.; done
          ls -R dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
        if: github.event_name == 'workflow_dispatch'